### ISSUE TITLE
Videos not appearing for download after extraction.

### ISSUE THREAD

**Issue by Anddrew914** [doshisid/codeschool-download#4]
Hi, I followed the guide as indicated, extracted several videos for download and I do have a courses.json file with the names of the videos I want to download. However when I open the program and select download videos the list of videos for download is empty. I've got the latest version of node and did a reinstall to see if that helped but no luck. I'm not really sure how I can help you recreate this issue locally but if there's any more info I can give let me know. I am making sure I run codeschool-download from the proper directory.

**Comment by aaditya-thakkar** [comment]
I am also facing the same issue. I selected the courses for extraction and all of them has videos array empty in the `courses.json` file. Hence it doesn't show anything to download.

**Comment by Anthony-Armfield** [comment]
I am also in the same boat. Node is 6.11.1, json file has empty arrays for videos. I am curious to know if this is an issue due to the free weekend. This was a note on another thread about a download software:

> Note: You'll have to have a paid plan in order to download all the videos available.

**Comment by sidoshi** [comment]
Sorry for late reply. I didn't receive any notifications for some reason. I will check #5 and merge it as soon as possible.

**Comment by sidoshi** [comment]
See #5
